In [19]:
import pandas as pd

data_product = pd.read_csv('.\data_products\data_products_all.csv', index_col=0)
data_category = pd.read_csv('.\data_products\data_category.csv', index_col=0)
data_rating = pd.read_csv('.\data_comments\data_comments_all_fixed.csv')

In [ ]:
data_product.info()

In [ ]:
data_product.isna().sum()

In [10]:
data_product.duplicated().sum()

np.int64(0)

In [22]:
data_product

,name,price,description,image,category_id,brand_id,brand_name,tiki_product_id
id,,,,,,,,
1,Máy đọc sách All New Kindle Paperwhite 5 (11th...,3680000,Amazon vừa chính thức ra mắt thế hệ tiếp theo ...,https://salt.tikicdn.com/cache/280x280/ts/prod...,1,147856,Kindle,125182567
2,"Điện thoại AI Samsung Galaxy S24 Ultra, Camera...",28020000,Điện thoại Samsung Galaxy S24 Ultra 5G- Hàng c...,https://salt.tikicdn.com/cache/280x280/ts/prod...,1,18802,Samsung,273947792
3,Máy đọc sách Kindle Scribe - Hàng chính hãng,12290000,Đọc và viết tự nhiên như khi làm trên giấyVới ...,https://salt.tikicdn.com/cache/280x280/ts/prod...,1,147856,Kindle,217640502
4,Máy đọc sách All New Kindle Paperwhite 5 (11th...,3976200,Amazon vừa chính thức ra mắt thế hệ tiếp the...,https://salt.tikicdn.com/cache/280x280/ts/prod...,1,147856,Kindle,252586291
5,Apple iPhone 11,9990000,"Nội dung về tính năngQuay video 4K, chụp ảnh c...",https://salt.tikicdn.com/cache/280x280/ts/prod...,1,17827,Apple,184036446
...,...,...,...,...,...,...,...,...
2058,Dây kháng lực tập gym tập mông Cabasports,40000,Cabasports chuyên phân phối các sản phẩm thể t...,https://salt.tikicdn.com/cache/280x280/ts/prod...,10,622141,CabaSports,193003821
2059,Giày Thể Thao Nam Biti's Hunter Street Mid DSM...,700000,Giày Thể Thao Nam Biti's Hunter Street Mid DSM...,https://salt.tikicdn.com/cache/280x280/ts/prod...,10,240925,Biti's,59080455
2060,[TẶNG HỘP CẦU] Cặp vợt cầu lông cán liền nhôm ...,932400,CÁC THÔNG SỐ CƠ BẢNThương hiệu: AgniteMã số: F...,https://salt.tikicdn.com/cache/280x280/ts/prod...,10,219519,Agnite,103209746
2061,Ghế Xếp Gọn Naturehike Câu Cá Dã Ngoại NH18X004-Y,520000,THÔNG SỐ KỸ THUẬTTên sản phẩm: Ghế câu cá dã n...,https://salt.tikicdn.com/cache/280x280/ts/prod...,10,149537,Naturehike,60423086
2062,Combo 3 Dụng Cụ Hỗ Trợ Tập Yoga - YOGA QG: 2...,119000,COMBO 3 DỤNG CỤ HỖ TRỢ TẬP YOGA1. Gạch Tập Yog...,https://salt.tikicdn.com/cache/280x280/ts/prod...,10,5083311,YOGA QG,117062013

In [13]:
data_rating.info()

<class 'pandas.DataFrame'>
Index: 19699 entries, Cực kì hài lòng to Cực kì hài lòng
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    19699 non-null  int64
 1   rating         19699 non-null  int64
 2   customer_name  19699 non-null  str
 3   product_id     19699 non-null  int64
dtypes: int64(3), str(1)
memory usage: 1.3+ MB

In [14]:
data_rating.isna().sum()

customer_id      0
rating           0
customer_name    0
product_id       0
dtype: int64

In [15]:
data_rating.duplicated().sum()

np.int64(1571)

In [23]:
if 'id' not in data_rating:
    data_rating.insert(0, 'id', range(1, len(data_rating)+1))

data_rating

,id,title,customer_id,rating,customer_name,product_id
0,1,Cực kì hài lòng,183920,5,Thái Ngọc Thắng,125182567
1,2,Cực kì hài lòng,1054513,5,Amy Nguyen,125182567
2,3,Hài lòng,1508657,4,Đoàn Hằng,125182567
3,4,Cực kì hài lòng,5795878,5,Cao Kiến Trung,125182567
4,5,Cực kì hài lòng,392927,5,Nguyễn Văn Phương,125182567
...,...,...,...,...,...,...
19694,19695,Cực kì hài lòng,6686817,5,Nguyễn Minh Vương,117062013
19695,19696,Cực kì hài lòng,8197700,5,Tam Ho,117062013
19696,19697,Cực kì hài lòng,12705959,5,trandai vinh,117062013
19697,19698,Cực kì hài lòng,20381830,5,Thảo Nguyễn,117062013
19698,19699,Cực kì hài lòng,25050624,5,Bùi Nhung,117062013

In [11]:
data_category

                                  name
id
1           Điện Thoại - Máy Tính Bảng
2                    Đồ Chơi - Mẹ & Bé
3                        Điện Gia Dụng
4                   Nhà Cửa - Đời Sống
5                        Thời Trang Nữ
6   Thiết Bị Kĩ Thuật Số - Phụ Kiện Số
7               Ô Tô - Xe Máy - Xe Đạp
8                   Làm Đẹp - Sức Khỏe
9                      Bách Hóa Online
10                 Thể Thao - Dã Ngoại

In [ ]:
from sqlalchemy import create_engine
import datetime

engine = create_engine('sqlite:///db.sqlite3', echo=False)


data_product['is_active'] = True
data_product['created_at'] = datetime.datetime.now()
data_product['updated_at'] = datetime.datetime.now()

data_category['created_at'] = datetime.datetime.now()
data_category['updated_at'] = datetime.datetime.now()

data_rating['created_at'] = datetime.datetime.now()


data_product.to_sql(
    name='store_product',       # Tên bảng trong database (app: store, model: Product)
    con=engine,                 
    if_exists='replace',         # Thêm dòng mới, giữ nguyên cấu trúc bảng
    # index=False                 # Bỏ qua cột index của DataFrame
)

data_category.to_sql(
    name='store_category',       # Tên bảng trong database (app: store, model: Category)
    con=engine,                 
    if_exists='replace',         # Thêm dòng mới, giữ nguyên cấu trúc bảng
    # index=False                 # Bỏ qua cột index của DataFrame
)

data_rating.to_sql(
    name='store_rating',       # Tên bảng trong database (app: store, model: Rating)
    con=engine,                 
    if_exists='replace',         # Thêm dòng mới, giữ nguyên cấu trúc bảng
    index=False                 # Bỏ qua cột index của DataFrame
)

print("Đã đẩy dữ liệu vào bảng store_product, store_category, store_rating trong SQLite thành công!")

Đã đẩy dữ liệu vào bảng store_product, store_category, store_rating trong SQLite thành công!